# -*- coding: utf-8 -*-
"""LLM.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nPSP3bSVy-Lw1GyUDfcHzXJjePDUfFee
"""

import pandas as pd
import google.generativeai as genai

# Load data
df = pd.read_csv('inv_urls_1.csv')

# Gemini API Configuration
API_KEY = "AIzaSyDh84oDU_7BczYpDNHUlEBw9inMj4Z36fo"
MODEL_NAME = "gemini-1.5-flash"

# Initialize Gemini API
genai.configure(api_key=API_KEY)
model = genai.GenerativeModel(MODEL_NAME)



# Function to generate article
def generate_location_article(brand, model_name, city, state):
    prompt = f"""
You are an advanced AI content writer specializing in writing SEO-friendly and engaging used car listing descriptions. Your task is to write a *500 to 600 word* article about a specific *car brand and model available in a particular U.S. city*, using a natural, informative, and human-like tone. This article will appear on a website to help potential buyers learn more about buying that vehicle in that location.

### Instructions:

1.Use a Professional and Direct Tone: Write in a helpful, expert tone. Use simple, direct language that is easy to understand. Do not use marketing jargon, overly descriptive "flowery" language, or storytelling.
2.Write a single, well-formed paragraph (5–6 lines, about 80–120 words) describing the car and its appeal in {city}, {state}. Do not use any line breaks, bullet points, subheadings, or separate sections. The entire output must be one continuous paragraph.
3.Your tone should be natural, human-like, and locally relevant.
4.Do not include repetitive phrases, or template language.
5.Mention the features of the car
6.Focus on what makes this car appealing in that city, mention a few features or trims, and add a touch of local flavor or lifestyle relevance.
7.Describe Common Local Options (approx. 120 words): Factually list the model years, engine types, and trim levels a buyer in that city is likely to find. Mention specific, popular features like Apple CarPlay, blind-spot monitoring, or cargo space.
8.⁠⁠Incorrect Example: Imagine cruising down the highway on a beautiful sunny day...
9.Avoid using generic intros like "This article helps you understand..." or "This guide covers...". Instead, vary your openings naturally — use a question, a bold claim, or dive right into local relevance.
10.Dont use the line "This guide will help you navigate..." or "This article helps you understand..." at all in output.
11.Every article should be completely different from the other.
12.Every output should have a different opening
13.Your entire output must be a single paragraph with no line breaks, no bullet points, and no subheadings. If you output more than one paragraph, your answer will be rejected.
14.No two output should have the same first word. If two or more output have the same first word then your answer will be rejected.

### Example Output 1:
The Ford F-150 is a familiar sight on Houston roads, where its mix of muscle and comfort fits right in with the city’s active lifestyle. Whether you’re looking at an XLT with the fuel-efficient EcoBoost or a Lariat with leather seats, you’ll find plenty of options for hauling gear, towing a boat, or just cruising the Beltway.
Houston’s market often features low-mileage trucks with 4x4 capability and tech like SYNC infotainment, making the F-150 a practical pick for both work and weekend escapes.

### Example Output 2:
A Honda CR-V in Houston means easy commutes and family trips, thanks to its roomy cabin and reliable performance. Local listings often include EX-L and Touring trims with heated seats, Apple CarPlay, and advanced safety features—perfect for navigating busy highways or escaping to Galveston.
With a reputation for low maintenance and strong resale value, the CR-V is a smart choice for Houstonians who want comfort and peace of mind in every drive.

### Example Output 3:
The Honda Civic is a go-to for Houston drivers who want style, efficiency, and easy parking downtown. You’ll find plenty of late-model Civics with turbo engines, Sport or EX trims, and features like touchscreen displays and remote start for those hot Texas afternoons.
With its reputation for reliability and low running costs, the Civic is a favorite for students, commuters, and anyone who values a smooth, stress-free ride in the city.

### Example Output 4:
In Houston, the Honda Accord stands out for drivers who appreciate comfort and technology on long commutes. Many local Accords feature EX-L or Touring trims, offering leather, sunroof, and adaptive cruise control, while hybrid options appeal to those watching fuel costs.
Its spacious interior and quiet ride make it ideal for families or professionals who want a sedan that’s both practical and refined for city living.

### Example Output 5:
Fort Worth drivers love the Ford F-150 for its rugged capability and everyday comfort. From XL work trucks to Platinum models loaded with features, local listings often include 4x4 and crew cab options that handle Texas roads with ease.
Whether you’re towing, hauling, or just enjoying a weekend adventure, the F-150’s blend of power and tech makes it a standout in Fort Worth’s busy used truck market.

*Brand:* {brand}
*Model:* {model_name}
*City, State:* {city}, {state}

*Output Article:*
"""
    response = model.generate_content(prompt)
    return response.text.strip() if response and hasattr(response, "text") else "Description not available."

# Process rows
filtered_rows = []

for _, row in df.iterrows():
    brand = row.get("brand", "")
    model_name = row.get("model", "")
    city = row.get("city", "")
    state = row.get("state", "")

    if not all([brand, model_name, city, state]):
        continue

    article = generate_location_article(brand, model_name, city, state)

    filtered_rows.append({
        "brand": brand,
        "model_name": model_name,
        "city": city,
        "state": state,
        "description": article
    })

# Create DataFrame after populating filtered_rows
df1 = pd.DataFrame(filtered_rows)
df1.to_csv('result15.csv', index=False)

